In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4795, 4691, 1943, 3751],
 [4795, 4691, 1943, 8181],
 [4795, 9864, 1943, 4355],
 [9222, 7112, 1544, 2584, 8765],
 [9222, 7112, 1544, 2584, 7070],
 [5699, 4795, 2496, 1943, 4167],
 [2853, 3970, 2707, 2584]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4795 4691 1943 3751]
 [   0    0    0    0 4795 4691 1943 8181]
 [   0    0    0    0 4795 9864 1943 4355]
 [   0    0    0 9222 7112 1544 2584 8765]
 [   0    0    0 9222 7112 1544 2584 7070]
 [   0    0    0 5699 4795 2496 1943 4167]
 [   0    0    0    0 2853 3970 2707 2584]]


In [10]:
## feature representation
dim=10

In [17]:
model=Sequential()

model.add(Embedding(voc_size,dim,input_length=sent_length))
model.build(input_shape=(None,sent_length))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step


array([[[-0.04177197,  0.02715454, -0.00142074, -0.00190531,
          0.01361691,  0.00331607,  0.02283729, -0.02584249,
          0.04720249,  0.04193124],
        [-0.04177197,  0.02715454, -0.00142074, -0.00190531,
          0.01361691,  0.00331607,  0.02283729, -0.02584249,
          0.04720249,  0.04193124],
        [-0.04177197,  0.02715454, -0.00142074, -0.00190531,
          0.01361691,  0.00331607,  0.02283729, -0.02584249,
          0.04720249,  0.04193124],
        [-0.04177197,  0.02715454, -0.00142074, -0.00190531,
          0.01361691,  0.00331607,  0.02283729, -0.02584249,
          0.04720249,  0.04193124],
        [ 0.03618368, -0.01325859, -0.0391075 , -0.03810734,
         -0.01340293, -0.01146353,  0.00881436, -0.01640088,
          0.03262449, -0.01607735],
        [-0.03088078, -0.04674672, -0.04389639,  0.03689054,
         -0.04001421,  0.03424374,  0.00710324, -0.01237289,
         -0.01661047,  0.02544249],
        [ 0.02519231,  0.04726053, -0.04395846,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4795, 4691, 1943, 3751])